sudo: required
language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install: 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -qq libcurl4-gnutls-dev openssl unixodbc unixodbc-dev libmysqlclient-dev liballegro5-dev liballegro-image5-dev liballegro-ttf5-dev liballegro-audio5-dev liballegro-acodec5-dev liballegro-dialog5-dev liballegro-physfs5-dev qt5-default qtbase5-dev qtmultimedia5-dev libqt5webkit5-dev libqt5serialport5-dev qtconnectivity5-dev qtdeclarative5-dev qtwebengine5-dev libqt5texttospeech5-dev libudev-dev mesa-common-dev freeglut3-dev ; fi
 
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install unixodbc ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql-connector-c ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install allegro ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt ; fi
 
script: 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd src && sudo ./buildgcc.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../extensions/ringcurl && ./gencode.sh && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringinternet && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringopenssl && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringmysql && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringodbc && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringsqlite && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringqt && ./gencode.sh && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringallegro && ./gencode.sh && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringfreeglut && ./gencode.sh && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ringopengl/opengl21 && ./gencode.sh && ./buildgcc.sh ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd src && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../extensions/ringallegro && ./gencode.sh && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../ringqt && ./gencodemac.sh && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../ringcurl && ./gencode.sh && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../ringfreeglut && ./gencode.sh && ./buildclang.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../ringopengl/opengl21 && ./gencode.sh && ./buildclang.sh ; fi
 
notifications:
 email: false